#!/bin/sh
# Author: Anton Hammerschmidt <Anton.Hammerschmidt@hs-augsburg.de>

. /lib/lsb/init-functions

do_start()
{
	echo "Starting powerpi server: "
	/bin/powerpi &
  	log_success_msg "done"
	return 0
}

do_stop()
{
	echo  "Stopping powerpi server: "
	pkill powerpi > /dev/null
	log_success_msg "done"
	return 0
}


### main logic ###
case "$1" in
  start)
        do_start
        ;;
  stop)
        do_stop
        ;;
  status)
        status powerpi
        ;;
  restart|reload|condrestart)
        do_stop
        do_start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
