all:
#	gcc -Wall -pedantic -o receive_kw receive_kw.cpp -L/usr/local/lib -lwiringPi -lstdc++
#	g++-4.7 -Wall -pedantic -o dht.bin ../database/sqdb.cpp bin.cpp dht.cpp -L/usr/local/lib -lwiringPi -lsqlite3 -ldl -std=c++11

	g++-4.7 -Wall -pedantic -o bin.cpp dht.cpp -L/usr/local/lib -lwiringPi -lsqlite3 -ldl -std=c++11

