all:
#	gcc -Wall -pedantic -o receive_kw receive_kw.cpp -L/usr/local/lib -lwiringPi -lstdc++
	gcc-4.7 -Wall -pedantic -o receive_kw ../database/sqdb.cpp receive_kw.cpp -L/usr/local/lib -lwiringPi -lstdc++ -std=c++11

clean:
	rm -rf recieve_kw